export const CONTENT_TYPE = {
    JSON: 'application/json',
    TEXT: 'text/plain',
    HTML: 'text/html',
    XML: 'application/xml',
    PDF: 'application/pdf',
    CSV: 'text/csv',
    IMAGE: 'image/jpeg',
    VIDEO: 'video/mp4',
    AUDIO: 'audio/mpeg',
    FORM_DATA: 'multipart/form-data',
    FORM_URLENCODED: 'application/x-www-form-urlencoded',
    APPLICATION_OCTET_STREAM: 'application/octet-stream',
    APPLICATION_X_PROTOBUF: 'application/x-protobuf',
    APPLICATION_X_PROTOBUF_WEB: 'application/x-protobuf-web',
    APPLICATION_X_PROTOBUF_WEB_WASM: 'application/x-protobuf-web-wasm',
    APPLICATION_X_PROTOBUF_WEB_WASM_WASM: 'application/x-protobuf-web-wasm-wasm',
    APPLICATION_X_PROTOBUF_WEB_WASM_WASM_WASM: 'application/x-protobuf-web-wasm-wasm-wasm',
}